--! This file is automatically generated. Do not modify, but checkout the generateQuestXp.lua script

---@type QuestXP
local QuestXP = QuestieLoader:ImportModule("QuestXP");

QuestXP.db = {
    [787] = {1, 40}, -- Classic: 1: 40->40->40 , TBC: 1: 60->50->60 , WOTLK: 1: 42/40
    [788] = {2, 170}, -- Classic: 2: 170->170->170 , TBC: 2: 170->150->170 , WOTLK: 2: 220/215
    [789] = {3, 250}, -- Classic: 3: 250->250->250 , TBC: 3: 250->250->250 , WOTLK: 3: 255/250
}
