-- Generated by a fixture tool. Do not edit by hand.
TalentsForeverBookData = {
  build = "1.60.1.79999",
  generated = "2026-01-01",
  codeVersion = "9",
  classes = {
    WARRIOR = {
      trees = {
        { name = "Fixture Tree", talents = {
          { node = 999001, name = "Fixture Talent", row = 1, col = 1, max = 2, spell = 999002 },
        } },
      },
    },
  },
}
